# Lists the art and music files in the game folder so the game can load them.
# Writes user-assets.js next to index.html. Run by Play.bat; safe to run any time.
$ErrorActionPreference = 'SilentlyContinue'
$base = (Get-Item -LiteralPath (Join-Path $PSScriptRoot '..')).FullName.TrimEnd('\')
Set-Location -LiteralPath $base

$exts = @('.png', '.jpg', '.jpeg', '.webp', '.gif', '.bmp', '.avif',
          '.mp3', '.ogg', '.wav', '.m4a', '.aac', '.oga', '.webm', '.flac')
$folders = @('naruto characters', 'naruto character', 'portraits', 'avatars',
             'sprite', 'sprites', 'characters', 'music', 'bgm')

$files = New-Object System.Collections.Generic.List[string]
foreach ($f in $folders) {
  $dir = Join-Path $base $f
  if (Test-Path -LiteralPath $dir) {
    Get-ChildItem -LiteralPath $dir -Recurse -File | Where-Object { $exts -contains $_.Extension.ToLower() } | ForEach-Object {
      $rel = $_.FullName.Substring($base.Length + 1) -replace '\\', '/'
      $files.Add($rel)
    }
  }
}

if ($files.Count -eq 0) { $json = '[]' } else { $json = ConvertTo-Json -InputObject @($files.ToArray()) -Compress }
$stamp = (Get-Date).ToString('s')
$js = "// Generated by Play.bat - lists your art files for the game.`r`nwindow.NR_USER_ASSETS = { generated: '$stamp', files: $json };`r`n"
[System.IO.File]::WriteAllText((Join-Path $base 'user-assets.js'), $js, (New-Object System.Text.UTF8Encoding $false))
Write-Host "  Found $($files.Count) art/music file(s)."
