#!/bin/sh
# Lists the art and music files in the game folder so the game can load them.
# Writes user-assets.js next to index.html. Run by play.sh; safe to run any time.
cd "$(dirname "$0")/.." || exit 1
out=user-assets.js
tmp="$out.tmp"
printf '// Generated by play.sh - lists your art files for the game.\nwindow.NR_USER_ASSETS = { generated: "%s", files: [\n' "$(date +%Y-%m-%dT%H:%M:%S)" > "$tmp"
for d in "naruto characters" "naruto character" portraits avatars sprite sprites characters music bgm; do
  [ -d "$d" ] || continue
  find "$d" -type f | while IFS= read -r f; do
    lower=$(printf '%s' "$f" | tr 'A-Z' 'a-z')
    case "$lower" in
      *.png|*.jpg|*.jpeg|*.webp|*.gif|*.bmp|*.avif|*.mp3|*.ogg|*.wav|*.m4a|*.aac|*.oga|*.webm|*.flac) ;;
      *) continue ;;
    esac
    esc=$(printf '%s' "$f" | sed 's/\\/\\\\/g; s/"/\\"/g')
    printf '  "%s",\n' "$esc"
  done >> "$tmp"
done
printf ']};\n' >> "$tmp"
mv "$tmp" "$out"
count=$(grep -c '^  "' "$out")
echo "Found $count art/music file(s)."
